csvexp1.py: csv2json.web
	notangle $< -L'#line %L "%F" %N' -Rcsvexp1.py > exp_src/csvexp1.py

jsonexp1.py: csv2json.web
	notangle $< -Rjsonexp1.py > exp_src/jsonexp1.py

csvfile.py: csv2json.web
	notangle $< -Rcsvfile.py > csvfile.py

c2j.py: csv2json.web
	notangle $< -Rc2j.py > c2j.py

csv2json.py: csv2json.web
	notangle $< -Rcsv2json.py > csv2json.py






